import  {
    Greetwhite,
    GreenPanel,
    Greenply,
    Gulf,
    Harison,
    Harvells,
    Hindware,
    HindwareBikes,
    HP,
    ICICI,
    JK,
    Jockey,
    Joyebike,
    Jsw,
    Kalpataru,
    KamlaPasand,
    KineticGreen,
    Kitply,
    Lic,
    Livfast,
    Lucetta,
    Lumerious,
    Luxvenux,
    Mecosporto,
    Microman,
    Maithon,
    MeghaMilk,
    Mobil,
    Motul,
    Nerolac,
    Netmods,
    Nippon,
    Nuvoco,
    OutStory,
    Parryware,
    PepsDream,
    PepsiCo,
    Philips,
    Polycab,
    PowerTrac,
    PrayagPlumbing,
    PertigueLogo,
    PrincePipe,
    PW,
    RalsonType,
    RelianceSmartBazar,
    RungtaSteel,
    Rupa,
    SalujaGold,
    SBI,
    Servo,
    SfBattery,
    SilverMotor,
    Sintex,
    Siscon,
    Siyaa,
    Sparx,
    Surya,
    Sympony,
    Tanishz,
    TataTiscon,
    Thumsump,
    Tomboy,
    TotalEnergatic,
    TvsType,
    Uclean,
    UltraTech,
    Unmaed,
    UsPopo,
    UtKarsh,
    Volveline,
    Vectus,
    VeedEngine,
    Vir,
    Wama,
    Wavin,
    Welspun
} from "../../public/clients"

const clientsData = [
    { url: Greetwhite, alt: 'Greetwhite' },
    { url: GreenPanel, alt: 'GreenPanel' },
    { url: Greenply, alt: 'Greenply' },
    { url: Gulf, alt: 'Gulf' },
    // Add other images here in the same format
    { url: Harison, alt: 'Harison Bath Fitting' },
    { url: Harvells, alt: 'Havells' },
    { url: Hindware, alt: 'Hindware italian' },
    { url: HindwareBikes, alt: 'Honda Bikes' },
    { url: HP, alt: 'HP' },
    { url: ICICI, alt: 'ICICI Prudential' },
    { url: JK, alt: 'JK Cement Wall max' },
    { url: Jockey, alt: 'Jockey' },
    { url: Joyebike, alt: 'Joyebike' },
    { url: Jsw, alt: 'jsw paint' },
    { url: Kalpataru, alt: 'Kalpataru Plywood' },
    { url: KamlaPasand, alt: 'Kamla Pasand' },
    { url: KineticGreen, alt: 'Kinetic Green' },
    { url: Kitply, alt: 'Kitply' },
    { url: Lic, alt: 'LIC' },
    { url: Livfast, alt: 'Livfast' },
    { url: Lucetta, alt: 'Livfast' },
    { url: Lumerious, alt: 'Luminous' },
    { url: Luxvenux, alt: 'Lux Venus' },
    { url: Mecosporto, alt: 'Macho sporto' },
    { url: Microman, alt: 'Macroman' },
    { url: Maithon, alt: 'maithonTMT' },
    { url: MeghaMilk, alt: 'Megha Milk' },
    { url: Mobil, alt: 'Megha Milk' },
    { url: Motul, alt: 'Mobil' },
    { url: Nerolac, alt: 'Nerolac' },
    { url: Netmods, alt: 'NEtmeds' },
    { url: Nippon, alt: 'Nippon Mutual Fund' },
    { url: Nuvoco, alt: 'Nuvoco cement - Concreto' },
    { url: OutStory, alt: 'our-story-bg-mob-new' },
    { url: Parryware, alt: 'Parryware' },
    { url: PepsDream, alt: 'Peps Dream' },
    { url: PepsiCo, alt: 'PepsiCo_logo' },
    { url: Philips, alt: 'Philips' },
    { url: Polycab, alt: 'Polycab' },
    { url: PowerTrac, alt: 'PowerTrac Escorts' },
    { url: PrayagPlumbing, alt: 'Prayag plumbing' },
    { url: PertigueLogo, alt: 'Prestige-Logo-PNG-HD' },
    { url: PrincePipe, alt: 'Prince pipes' },
    { url: PW, alt: 'PW' },
    { url: RalsonType, alt: 'Ralson tyres' },
    { url: RelianceSmartBazar, alt: 'Reliance Smart Bazaar' },
    { url: RungtaSteel, alt: 'Rungta steel' },
    { url: Rupa, alt: 'Rupa' },
    { url: SalujaGold, alt: 'salujaGold' },
    { url: SBI, alt: 'SBI Mutual Fund' },
    { url: Servo, alt: 'Servo' },
    { url: SfBattery, alt: 'SF batteries' },
    { url: SilverMotor, alt: 'Silver motors' },
    { url: Sintex, alt: 'Sintex' },
    { url: Siscon, alt: 'Siscon TMT' },
    { url: Siyaa, alt: 'Siyaa electricals' },
    { url: Sparx, alt: 'Sparx' },
    { url: Surya, alt: 'Surya' },
    { url: Sympony, alt: 'Symphony' },
    { url: Tanishz, alt: 'Tanishq' },
    { url: TataTiscon, alt: 'Tata Tiscon' },
    { url: Thumsump, alt: 'Thumsup' },
    { url: Tomboy, alt: 'Tomboy' },
    { url: TotalEnergatic, alt: 'Total Energies' },
    { url: TvsType, alt: 'tvs tyre' },
    { url: Uclean, alt: 'UClean' },
    { url: UltraTech, alt: 'Ultratechcement' },
    { url: Unmaed, alt: 'unnamed' },
    { url: UsPopo, alt: 'US polo' },
    { url: UtKarsh, alt: 'Utkarsh pipes' },
    { url: Volveline, alt: 'Valvoline oil' },
    { url: Vectus, alt: 'Vectus' },
    { url: VeedEngine, alt: 'Veed engine oil' },
    { url: Vir, alt: 'Vir Laminate' },
    { url: Wama, alt: 'Wama Steels' },
    { url: Wavin, alt: 'wavin' },
    { url: Welspun, alt: 'Welspun' },
];

export default clientsData;
